# Generated by Django 4.2.2 on 2023-06-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_products_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
