# Generated by Django 4.2.2 on 2023-06-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_products_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
